name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: Run tests
        run: |
          docker run --rm my-fastapi-app pytest # Adjust this command based on your testing setup
      
      - name: Run docker file
        run: |
          docker run -d my-fastapi-app